/**
 * ODM Data Analysis - a tool for the automatic validation, monitoring and
 * generation of generic descriptive statistics of clinical data.
 * 
 * Copyright (c) 2017 Institut für Medizinische Informatik, Münster
 *
 * ODM Data Analysis is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by the
 * Free Software Foundation, version 3.
 *
 * ODM Data Analysis is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for 
 * more details.
 *
 * You should have received a copy of the GNU General Public License in the file
 * COPYING along with ODM Data Analysis. If not, see <http://www.gnu.org/licenses/>.
 */
SET DB_CLOSE_DELAY -1;   
;             
CREATE USER IF NOT EXISTS SA SALT '5bb3a4867f1baf34' HASH '2d9da8b4f38592d2d2f9295fc5151384462dc5c8026152655b860de8aa8888ba' ADMIN;           
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 1;       
CREATE SEQUENCE PUBLIC.HILO_SEQEUNCE START WITH 1;            
CREATE MEMORY TABLE PUBLIC.CLINICALDATA(
    ID BIGINT NOT NULL,
    FORMREPEATKEY VARCHAR(255),
    ITEMGROUPREPEATKEY VARCHAR(255),
    STUDYEVENTREPEATKEY VARCHAR(255),
    SUBJECTKEY VARCHAR(255),
    VALUE TEXT,
    CLINICALSUBJECTDATA_ID BIGINT,
    METAFORM_ID BIGINT,
    METAITEM_ID BIGINT,
    METAITEMGROUP_ID BIGINT,
    METASTUDYEVENT_ID BIGINT
);  
ALTER TABLE PUBLIC.CLINICALDATA ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLINICALDATA;            
CREATE MEMORY TABLE PUBLIC.CLINICALFORMDATA(
    ID BIGINT NOT NULL,
    COMPLETENESS BOOLEAN,
    REPEATKEY VARCHAR(255),
    CLINICALSTUDYEVENTDATA_ID BIGINT,
    METAFORM_ID BIGINT
);      
ALTER TABLE PUBLIC.CLINICALFORMDATA ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLINICALFORMDATA;        
CREATE MEMORY TABLE PUBLIC.CLINICALITEMDATA(
    ID BIGINT NOT NULL,
    COMPLETENESS BOOLEAN,
    VALUE TEXT,
    CLINICALITEMGROUPDATA_ID BIGINT,
    METAITEM_ID BIGINT
);   
ALTER TABLE PUBLIC.CLINICALITEMDATA ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLINICALITEMDATA;        
CREATE MEMORY TABLE PUBLIC.CLINICALITEMGROUPDATA(
    ID BIGINT NOT NULL,
    COMPLETENESS BOOLEAN,
    REPEATKEY VARCHAR(255),
    CLINICALFORMDATA_ID BIGINT,
    METAITEMGROUP_ID BIGINT
);  
ALTER TABLE PUBLIC.CLINICALITEMGROUPDATA ADD CONSTRAINT PUBLIC.CONSTRAINT_F5 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLINICALITEMGROUPDATA;   
CREATE MEMORY TABLE PUBLIC.CLINICALSTUDYEVENTDATA(
    ID BIGINT NOT NULL,
    COMPLETENESS BOOLEAN,
    REPEATKEY VARCHAR(255),
    CLINICALSUBJECTDATA_ID BIGINT,
    METASTUDYEVENT_ID BIGINT
);             
ALTER TABLE PUBLIC.CLINICALSTUDYEVENTDATA ADD CONSTRAINT PUBLIC.CONSTRAINT_F4 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLINICALSTUDYEVENTDATA;  
CREATE MEMORY TABLE PUBLIC.CLINICALSUBJECTDATA(
    ID BIGINT NOT NULL,
    COMPLETENESS BOOLEAN,
    SUBJECTKEY VARCHAR(255)
);  
ALTER TABLE PUBLIC.CLINICALSUBJECTDATA ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLINICALSUBJECTDATA;     
CREATE MEMORY TABLE PUBLIC.CODELIST(
    ID BIGINT NOT NULL,
    ORDERNUMBER INTEGER,
    OID VARCHAR(255),
    DATATYPE VARCHAR(255),
    NAME VARCHAR(255)
); 
ALTER TABLE PUBLIC.CODELIST ADD CONSTRAINT PUBLIC.CONSTRAINT_FA PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CODELIST;
CREATE MEMORY TABLE PUBLIC.CODELISTITEM(
    ID BIGINT NOT NULL,
    CODEDVALUE VARCHAR(255),
    ORDERNUMBER INTEGER,
    RANK FLOAT,
    CODELIST_ID BIGINT
);
ALTER TABLE PUBLIC.CODELISTITEM ADD CONSTRAINT PUBLIC.CONSTRAINT_4E PRIMARY KEY(ID);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CODELISTITEM;            
CREATE MEMORY TABLE PUBLIC.INVALIDCLINICALDATA(
    ID BIGINT NOT NULL,
    FORMREPEATKEY VARCHAR(255),
    ITEMGROUPREPEATKEY VARCHAR(255),
    METAFORMOID VARCHAR(255),
    METAITEMGROUPOID VARCHAR(255),
    METAITEMOID VARCHAR(255),
    METASTUDYEVENTOID VARCHAR(255),
    REASON TEXT,
    STUDYEVENTREPEATKEY VARCHAR(255),
    SUBJECTKEY VARCHAR(255),
    VALUE TEXT,
    CLINICALSUBJECTDATA_ID BIGINT
); 
ALTER TABLE PUBLIC.INVALIDCLINICALDATA ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.INVALIDCLINICALDATA;     
CREATE MEMORY TABLE PUBLIC.METAFORM(
    ID BIGINT NOT NULL,
    ORDERNUMBER INTEGER,
    OID VARCHAR(255),
    DATACOUNTS INTEGER,
    MANDATORY BOOLEAN,
    MANDATORYCOMPLETENESS VARCHAR(255),
    NAME VARCHAR(255),
    REPEATING BOOLEAN,
    SUBJECTCOUNTS INTEGER,
    METASTUDYEVENT_ID BIGINT
);
ALTER TABLE PUBLIC.METAFORM ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.METAFORM;
CREATE MEMORY TABLE PUBLIC.METAITEM(
    ID BIGINT NOT NULL,
    ORDERNUMBER INTEGER,
    OID VARCHAR(255),
    DATACOUNTS INTEGER,
    DATATYPE INTEGER,
    MANDATORY BOOLEAN,
    MANDATORYCOMPLETENESS VARCHAR(255),
    NAME VARCHAR(255),
    SUBJECTCOUNTS INTEGER,
    CODELIST_ID BIGINT,
    METAITEMGROUP_ID BIGINT
);         
ALTER TABLE PUBLIC.METAITEM ADD CONSTRAINT PUBLIC.CONSTRAINT_13 PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.METAITEM;
CREATE MEMORY TABLE PUBLIC.METAITEMGROUP(
    ID BIGINT NOT NULL,
    ORDERNUMBER INTEGER,
    OID VARCHAR(255),
    DATACOUNTS INTEGER,
    MANDATORY BOOLEAN,
    MANDATORYCOMPLETENESS VARCHAR(255),
    NAME VARCHAR(255),
    REPEATING BOOLEAN,
    SUBJECTCOUNTS INTEGER,
    METAFORM_ID BIGINT
); 
ALTER TABLE PUBLIC.METAITEMGROUP ADD CONSTRAINT PUBLIC.CONSTRAINT_D8 PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.METAITEMGROUP;           
CREATE MEMORY TABLE PUBLIC.METASTUDY(
    ID BIGINT NOT NULL,
    ORDERNUMBER INTEGER,
    OID VARCHAR(255)
);    
ALTER TABLE PUBLIC.METASTUDY ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.METASTUDY;               
CREATE MEMORY TABLE PUBLIC.METASTUDYEVENT(
    ID BIGINT NOT NULL,
    ORDERNUMBER INTEGER,
    OID VARCHAR(255),
    DATACOUNTS INTEGER,
    MANDATORY BOOLEAN,
    MANDATORYCOMPLETENESS VARCHAR(255),
    NAME VARCHAR(255),
    REPEATING BOOLEAN,
    SUBJECTCOUNTS INTEGER,
    TYPE VARCHAR(255),
    METASTUDY_ID BIGINT
);       
ALTER TABLE PUBLIC.METASTUDYEVENT ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.METASTUDYEVENT;          
CREATE MEMORY TABLE PUBLIC.ODMFILE(
    ID BIGINT NOT NULL,
    OID TEXT,
    UPLOADTIME TIMESTAMP
);     
ALTER TABLE PUBLIC.ODMFILE ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ODMFILE; 
CREATE MEMORY TABLE PUBLIC.TRANSLATEDTEXT(
    ID BIGINT NOT NULL,
    LANGATTRIBUTE VARCHAR(255),
    TEXT TEXT,
    CODELISTITEM_ID BIGINT,
    METAITEM_ID BIGINT
);         
ALTER TABLE PUBLIC.TRANSLATEDTEXT ADD CONSTRAINT PUBLIC.CONSTRAINT_42 PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TRANSLATEDTEXT;          
ALTER TABLE PUBLIC.CLINICALSTUDYEVENTDATA ADD CONSTRAINT PUBLIC.FKEJF9AUXMDHJ1YTX5RF22AV33N FOREIGN KEY(CLINICALSUBJECTDATA_ID) REFERENCES PUBLIC.CLINICALSUBJECTDATA(ID) ON DELETE CASCADE NOCHECK;          
ALTER TABLE PUBLIC.CLINICALDATA ADD CONSTRAINT PUBLIC.FKMBJN4XKOJBAJJB8L98GG30A80 FOREIGN KEY(METAFORM_ID) REFERENCES PUBLIC.METAFORM(ID) ON DELETE CASCADE NOCHECK;          
ALTER TABLE PUBLIC.CODELISTITEM ADD CONSTRAINT PUBLIC.FKSR2X6QWU9T3WWTCCH82M1XRXJ FOREIGN KEY(CODELIST_ID) REFERENCES PUBLIC.CODELIST(ID) ON DELETE CASCADE NOCHECK;          
ALTER TABLE PUBLIC.CLINICALFORMDATA ADD CONSTRAINT PUBLIC.FKNGCTN732EO4W4JB7IQNOK7Y5B FOREIGN KEY(CLINICALSTUDYEVENTDATA_ID) REFERENCES PUBLIC.CLINICALSTUDYEVENTDATA(ID) ON DELETE CASCADE NOCHECK;          
ALTER TABLE PUBLIC.TRANSLATEDTEXT ADD CONSTRAINT PUBLIC.FK3F4A56PG2H40M68FQVHUVO2G4 FOREIGN KEY(METAITEM_ID) REFERENCES PUBLIC.METAITEM(ID) ON DELETE CASCADE NOCHECK;        
ALTER TABLE PUBLIC.METAITEM ADD CONSTRAINT PUBLIC.FKIJ8CI36Y97N1J5NHEK2WYLQCE FOREIGN KEY(CODELIST_ID) REFERENCES PUBLIC.CODELIST(ID) ON DELETE CASCADE NOCHECK;              
ALTER TABLE PUBLIC.METASTUDYEVENT ADD CONSTRAINT PUBLIC.FKPVCBWP9P3IRETIAPSRJCJ9LOG FOREIGN KEY(METASTUDY_ID) REFERENCES PUBLIC.METASTUDY(ID) ON DELETE CASCADE NOCHECK;      
ALTER TABLE PUBLIC.CLINICALFORMDATA ADD CONSTRAINT PUBLIC.FKMV4FU6VXV5047SFNEU79M586X FOREIGN KEY(METAFORM_ID) REFERENCES PUBLIC.METAFORM(ID) ON DELETE CASCADE NOCHECK;      
ALTER TABLE PUBLIC.METAFORM ADD CONSTRAINT PUBLIC.FKFDSJRJUFGWEO1L87JOF48458B FOREIGN KEY(METASTUDYEVENT_ID) REFERENCES PUBLIC.METASTUDYEVENT(ID) ON DELETE CASCADE NOCHECK;  
ALTER TABLE PUBLIC.CLINICALITEMDATA ADD CONSTRAINT PUBLIC.FKT0AUNCUIK83QSB18L0A3LYGF5 FOREIGN KEY(METAITEM_ID) REFERENCES PUBLIC.METAITEM(ID) ON DELETE CASCADE NOCHECK;      
ALTER TABLE PUBLIC.METAITEMGROUP ADD CONSTRAINT PUBLIC.FKIONQNJR4KAWQMI8W17JLJYCO6 FOREIGN KEY(METAFORM_ID) REFERENCES PUBLIC.METAFORM(ID) ON DELETE CASCADE NOCHECK;         
ALTER TABLE PUBLIC.METAITEM ADD CONSTRAINT PUBLIC.FK75EMWGSCEKA38WDO44M1IDTTG FOREIGN KEY(METAITEMGROUP_ID) REFERENCES PUBLIC.METAITEMGROUP(ID) ON DELETE CASCADE NOCHECK;    
ALTER TABLE PUBLIC.CLINICALITEMGROUPDATA ADD CONSTRAINT PUBLIC.FKLHNNXA1HN754CWR1AOKG4GF6Y FOREIGN KEY(METAITEMGROUP_ID) REFERENCES PUBLIC.METAITEMGROUP(ID) ON DELETE CASCADE NOCHECK;       
ALTER TABLE PUBLIC.INVALIDCLINICALDATA ADD CONSTRAINT PUBLIC.FKP0OT65CVYCFBU7MSXG4655NPB FOREIGN KEY(CLINICALSUBJECTDATA_ID) REFERENCES PUBLIC.CLINICALSUBJECTDATA(ID) ON DELETE CASCADE NOCHECK;             
ALTER TABLE PUBLIC.CLINICALITEMGROUPDATA ADD CONSTRAINT PUBLIC.FK2AR7GUD82OYTJOSFJ6YGF41U4 FOREIGN KEY(CLINICALFORMDATA_ID) REFERENCES PUBLIC.CLINICALFORMDATA(ID) ON DELETE CASCADE NOCHECK; 
ALTER TABLE PUBLIC.CLINICALDATA ADD CONSTRAINT PUBLIC.FKMSCO5PC56NT5O4HF2VQXNKTTU FOREIGN KEY(METAITEMGROUP_ID) REFERENCES PUBLIC.METAITEMGROUP(ID) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.CLINICALDATA ADD CONSTRAINT PUBLIC.FKBMN7N818SWBIDNDLG4DY65GAE FOREIGN KEY(METASTUDYEVENT_ID) REFERENCES PUBLIC.METASTUDYEVENT(ID) ON DELETE CASCADE NOCHECK;              
ALTER TABLE PUBLIC.CLINICALDATA ADD CONSTRAINT PUBLIC.FKS9XCXO7VJ5CBBSQON5C0QCCH4 FOREIGN KEY(CLINICALSUBJECTDATA_ID) REFERENCES PUBLIC.CLINICALSUBJECTDATA(ID) ON DELETE CASCADE NOCHECK;    
ALTER TABLE PUBLIC.CLINICALITEMDATA ADD CONSTRAINT PUBLIC.FK3CRVCQ4GYDKRMN1P8P71MRE02 FOREIGN KEY(CLINICALITEMGROUPDATA_ID) REFERENCES PUBLIC.CLINICALITEMGROUPDATA(ID) ON DELETE CASCADE NOCHECK;            
ALTER TABLE PUBLIC.TRANSLATEDTEXT ADD CONSTRAINT PUBLIC.FK1WSRQ0P7NUQMPUXNLY3R8HWFU FOREIGN KEY(CODELISTITEM_ID) REFERENCES PUBLIC.CODELISTITEM(ID) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.CLINICALSTUDYEVENTDATA ADD CONSTRAINT PUBLIC.FK6YSBMBQSKX3T9BAGO260IDNJY FOREIGN KEY(METASTUDYEVENT_ID) REFERENCES PUBLIC.METASTUDYEVENT(ID) ON DELETE CASCADE NOCHECK;    
ALTER TABLE PUBLIC.CLINICALDATA ADD CONSTRAINT PUBLIC.FK2QYJ9PI8R710W07RSXB734SS7 FOREIGN KEY(METAITEM_ID) REFERENCES PUBLIC.METAITEM(ID) ON DELETE CASCADE NOCHECK;          
